# Generated by Django 4.2.5 on 2023-09-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_users', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.TextField(max_length=255)),
                ('ages', models.IntegerField()),
            ],
        ),
    ]
